# Generated by Django 6.0.1 on 2026-02-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
