# Generated by Django 6.0.1 on 2026-02-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_bill_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='extended_months',
            field=models.IntegerField(default=0),
        ),
    ]
